### ISSUE TITLE
ERROR loading table D from disk -> No such file or directory

### ISSUE THREAD

**Issue by cpbentley** [Egor-Skriptunoff/LGS_extension#2]
ERROR loading table D from disk
cannot open C:\LGS extension\D_for_opera.lua: No such file or directory

Windows 10. LGS 9.00.42

If I create D_for_opera.lua file empty, things will work out. 

Maybe just explain that in the readme

**Comment by Egor-Skriptunoff** [comment]
Indeed, when you run a profile for the first time, there is no such file yet, hence the error.
The file will be created on profile exit.
When you run the profile for the second time, the file must already exist and no error message must be shown.
So, you will see this error message once for every new profile.
You should just ignore this error message for the first time.
No need to create the file manually.

Yes, I must clarify it in the the readme.
Thanks for pointing it out.

**Comment by sallesxd** [comment]
Egor, im Salles From stackoverflow, if you have a way that i can drop you a coffee, tell me, ill check here later. Thank you for being awesome.

**Comment by Egor-Skriptunoff** [comment]
@sallesxd - I'm glad your problem is solved.  I don't accept donations for my answers on SO.

**Comment by SimonMarchand** [comment]
Hey, I know the code was not updated for 3 months, but the "Save to Table D" isn't working anymore with G Hub since they updated the LUA version. I found out that the `local t = loadstring("return "..expr)()` in the function enum_standard_tables should use load() now. But I now have a nil value for the variable tbl in `local tbl = list_of_known_values[table.remove(stack_of_tables_to_parse)]`, I tried to just skip if nil. I don't have anymore error message but it still not create the file D_xxxx.lua
There was also an issue with the function math.frexp that was not found so I added a local one
```
math.frexp = math.frexp or
  function(x)
     local e = 0
     if x == 0 then
        return x, e
     end
     local sign = x < 0 and -1 or 1
     x = x * sign
     while x >= 1 do
        x = x / 2
        e = e + 1
     end
     while x < 0.5 do
        x = x * 2
        e = e - 1
     end
     return x * sign, e
  end
```
I can code but it's my first time in LUA and I'm not exactly sure what is the issue. If you could help that would be really nice :D!
Thanks for the work 👍

**Comment by Egor-Skriptunoff** [comment]
@SimonMarchand - Yes, the code needs to be rewritten because of new Lua version.  
I will do it some day or other.
